[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/count"
  to = "/.netlify/functions/count"
  status = 200

[[redirects]]
  from = "/api/signers"
  to = "/.netlify/functions/signers"
  status = 200

[[redirects]]
  from = "/api/sign"
  to = "/.netlify/functions/sign"
  status = 200
